spring.application.name=gymtracker
spring.datasource.url=jdbc:postgresql://localhost:5432/gymtracker
spring.datasource.username=gymuser
spring.datasource.password=devuka

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true